Public Class Form1
    Dim DirSelected As Integer

    Private Sub Button1_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Button1.Click
        FolderBrowserDialog1.ShowDialog()
        Label3.Text = FolderBrowserDialog1.SelectedPath & "\" & TextBox2.Text
        Button2.Enabled = True
        DirSelected = 1
    End Sub

    Private Sub TextBox2_TextChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles TextBox2.TextChanged
        If DirSelected = 1 Then
            Label3.Text = FolderBrowserDialog1.SelectedPath & "\" & TextBox2.Text
        End If
    End Sub


    Private Sub Button2_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Button2.Click
        Dim retvalue As Object

        Dim ProjectDirectory As String
        Dim ProjectName As String
        Dim Project_project_fileFullPath As Object
        Dim Project_f28377sHeadersDir As String
        Dim Project_f28377sSrcDir As String

        Dim Project_cproject_fileFullPath As Object
        Dim Project_ccsproject_fileFullPath As Object
        Dim Project_copybat_fileFullPath As Object

        Dim ProjectSubDirectory As String
        Dim ProjectSub_settings_Dir As String
        Dim ProjectSub_Debug_Dir As String
        Dim ProjectSub_targetConfigs As String
        Dim Project_v140_Dir As String
        Dim Project_DSP28377_common_Dir As String
        Dim Project_DSP28377_common_cmd_Dir As String
        Dim Project_DSP28377_common_include_Dir As String
        Dim Project_DSP28377_common_source_Dir As String
        Dim Project_DSP28377_headers_Dir As String
        Dim Project_DSP28377_headers_cmd_Dir As String
        Dim Project_DSP28377_headers_include_Dir As String
        Dim Project_DSP28377_headers_source_Dir As String
        Dim Project_matlab_Dir As String

        Dim Matlab_funcGE420_serialread_fileFullPath As String
        Dim Matlab_funcGE420_serialread_address_fileFullPath As String
        Dim Matlab_funcGE420_serialwrite_fileFullPath As String
        Dim Matlab_funcGE420_serialwrite_address_fileFullPath As String
        Dim Matlab_funcGE420_serialwrite_echo_fileFullPath As String
        Dim Matlab_funcGE420_serialwrite_echo_address_fileFullPath As String
        Dim Matlab_funcGE420_serial_ListVars_fileFullPath As String


        Dim i As Integer
        Dim Drive As String
        Dim PathStr As String, NameStr As String

        On Error GoTo SaveError

        ProjectName = TextBox2.Text
        Drive = Mid(FolderBrowserDialog1.SelectedPath, 1, 2)
        PathStr = Mid(FolderBrowserDialog1.SelectedPath, 4)
        NameStr = ProjectName

        ' Check for bad characters in path
        For i = 0 To PathStr.Length - 1
            If Not ((Asc(PathStr(i)) > 47 And Asc(PathStr(i)) < 58) _
                    Or (Asc(PathStr(i)) > 64 And Asc(PathStr(i)) < 91) _
                    Or (Asc(PathStr(i)) > 96 And Asc(PathStr(i)) < 123) _
                    Or Asc(PathStr(i)) = 92 Or Asc(PathStr(i)) = 95) Then
                MsgBox("Path contains a non-alphanumeric character or a space." & _
                    Chr(13) & Chr(10) & "Please choose a different path.")

                Exit Sub
            End If
        Next i

        ' Check for bad characters in project name
        For i = 0 To NameStr.Length - 1
            If Not ((Asc(NameStr(i)) > 47 And Asc(NameStr(i)) < 58) _
                    Or (Asc(NameStr(i)) > 64 And Asc(NameStr(i)) < 91) _
                    Or (Asc(NameStr(i)) > 96 And Asc(NameStr(i)) < 123) _
                    Or Asc(NameStr(i)) = 92 Or Asc(NameStr(i)) = 95) Then
                MsgBox("Project name contains a non-alphanumeric character or a space." & _
                    Chr(13) & Chr(10) & "Please choose a different name.")

                Exit Sub
            End If
        Next i


        ProjectDirectory = FolderBrowserDialog1.SelectedPath & "\" & ProjectName & "\"
        ProjectSubDirectory = ProjectDirectory & ProjectName & "Project\"
        ProjectSub_settings_Dir = ProjectSubDirectory & ".settings\"
        ProjectSub_targetConfigs = ProjectSubDirectory & "targetConfigs\"
        ProjectSub_Debug_Dir = ProjectSubDirectory & "Debug\"

        Project_f28377sHeadersDir = ProjectDirectory & "F28377sHeaders\"
        Project_f28377sSrcDir = ProjectDirectory & "F28377sSrc\"
        Project_matlab_Dir = ProjectDirectory & "matlab\"

        Project_project_fileFullPath = ProjectSubDirectory & ".project"
        Project_cproject_fileFullPath = ProjectSubDirectory & ".cproject"
        Project_ccsproject_fileFullPath = ProjectSubDirectory & ".ccsproject"
        Project_copybat_fileFullPath = ProjectDirectory & "tmpcopy.bat"

        Project_v140_Dir = ProjectDirectory & "v140\"
        Project_DSP28377_common_Dir = Project_v140_Dir & "F2837xS_common\"
        Project_DSP28377_common_cmd_Dir = Project_DSP28377_common_Dir & "cmd\"
        Project_DSP28377_common_include_Dir = Project_DSP28377_common_Dir & "include\"
        Project_DSP28377_common_source_Dir = Project_DSP28377_common_Dir & "source\"
        Project_DSP28377_headers_Dir = Project_v140_Dir & "F2837xS_headers\"
        Project_DSP28377_headers_cmd_Dir = Project_DSP28377_headers_Dir & "cmd\"
        Project_DSP28377_headers_include_Dir = Project_DSP28377_headers_Dir & "include\"
        Project_DSP28377_headers_source_Dir = Project_DSP28377_headers_Dir & "source\"

        Matlab_funcGE420_serialread_fileFullPath = Project_matlab_Dir & "GE420_serialread.m"
        Matlab_funcGE420_serialread_address_fileFullPath = Project_matlab_Dir & "GE420_serialread_address.m"
        Matlab_funcGE420_serialwrite_fileFullPath = Project_matlab_Dir & "GE420_serialwrite.m"
        Matlab_funcGE420_serialwrite_address_fileFullPath = Project_matlab_Dir & "GE420_serialwrite_address.m"
        Matlab_funcGE420_serialwrite_echo_fileFullPath = Project_matlab_Dir & "GE420_serialwrite_echo.m"
        Matlab_funcGE420_serialwrite_echo_address_fileFullPath = Project_matlab_Dir & "GE420_serialwrite_echo_address.m"
        Matlab_funcGE420_serial_ListVars_fileFullPath = Project_matlab_Dir & "GE420_serial_ListVars.m"


        MkDir(ProjectDirectory)
        MkDir(ProjectSubDirectory)
        MkDir(ProjectSub_settings_Dir)
        MkDir(ProjectSub_Debug_Dir)
        MkDir(ProjectSub_targetConfigs)

        MkDir(Project_f28377sHeadersDir)
        MkDir(Project_f28377sSrcDir)
        MkDir(Project_matlab_Dir)
        MkDir(Project_v140_Dir)
        MkDir(Project_DSP28377_common_Dir)
        MkDir(Project_DSP28377_common_cmd_Dir)
        MkDir(Project_DSP28377_common_include_Dir)
        MkDir(Project_DSP28377_common_source_Dir)
        MkDir(Project_DSP28377_headers_Dir)
        MkDir(Project_DSP28377_headers_cmd_Dir)
        MkDir(Project_DSP28377_headers_include_Dir)
        MkDir(Project_DSP28377_headers_source_Dir)


        GoTo NoError
SaveError:
        'MsgBox "Error" & CStr(Err.Number)
        If Err.Number = 75 Then
            MsgBox("Directory already Exists!")
            GoTo NoWrite
        End If
NoError:

        FileOpen(1, Project_project_fileFullPath, OpenMode.Output)

        PrintLine(1, "<?xml version=""1.0"" encoding=""UTF-8""?>")
        PrintLine(1, "<projectDescription>")
        PrintLine(1, "	<name>" & ProjectName & "</name>")
        PrintLine(1, "	<comment></comment>")
        PrintLine(1, "	<projects>")
        PrintLine(1, "	</projects>")
        PrintLine(1, "	<buildSpec>")
        PrintLine(1, "		<buildCommand>")
        PrintLine(1, "			<name>org.eclipse.cdt.managedbuilder.core.genmakebuilder</name>")
        PrintLine(1, "			<arguments>")
        PrintLine(1, "			</arguments>")
        PrintLine(1, "		</buildCommand>")
        PrintLine(1, "		<buildCommand>")
        PrintLine(1, "			<name>org.eclipse.cdt.managedbuilder.core.ScannerConfigBuilder</name>")
        PrintLine(1, "			<triggers>full,incremental,</triggers>")
        PrintLine(1, "			<arguments>")
        PrintLine(1, "			</arguments>")
        PrintLine(1, "		</buildCommand>")
        PrintLine(1, "	</buildSpec>")
        PrintLine(1, "	<natures>")
        PrintLine(1, "		<nature>org.eclipse.rtsc.xdctools.buildDefinitions.XDC.xdcNature</nature>")
        PrintLine(1, "		<nature>com.ti.ccstudio.core.ccsNature</nature>")
        PrintLine(1, "		<nature>org.eclipse.cdt.core.cnature</nature>")
        PrintLine(1, "		<nature>org.eclipse.cdt.managedbuilder.core.managedBuildNature</nature>")
        PrintLine(1, "		<nature>org.eclipse.cdt.core.ccnature</nature>")
        PrintLine(1, "		<nature>org.eclipse.cdt.managedbuilder.core.ScannerConfigNature</nature>")
        PrintLine(1, "	</natures>")
        PrintLine(1, "	<linkedResources>")
        PrintLine(1, "		<link>")
        PrintLine(1, "			<name>F2837xS_Adc.c</name>")
        PrintLine(1, "			<type>1</type>")
        PrintLine(1, "			<locationURI>PARENT-1-PROJECT_LOC/v140/F2837xS_common/source/F2837xS_Adc.c</locationURI>")
        PrintLine(1, "		</link>")
        PrintLine(1, "		<link>")
        PrintLine(1, "			<name>F2837xS_CodeStartBranch.asm</name>")
        PrintLine(1, "			<type>1</type>")
        PrintLine(1, "			<locationURI>PARENT-1-PROJECT_LOC/v140/F2837xS_common/source/F2837xS_CodeStartBranch.asm</locationURI>")
        PrintLine(1, "		</link>")
        PrintLine(1, "		<link>")
        PrintLine(1, "			<name>F2837xS_EPwm.c</name>")
        PrintLine(1, "			<type>1</type>")
        PrintLine(1, "			<locationURI>PARENT-1-PROJECT_LOC/v140/F2837xS_common/source/F2837xS_EPwm.c</locationURI>")
        PrintLine(1, "		</link>")
        PrintLine(1, "		<link>")
        PrintLine(1, "			<name>F2837xS_GlobalVariableDefs.c</name>")
        PrintLine(1, "			<type>1</type>")
        PrintLine(1, "			<locationURI>PARENT-1-PROJECT_LOC/v140/F2837xS_headers/source/F2837xS_GlobalVariableDefs.c</locationURI>")
        PrintLine(1, "		</link>")
        PrintLine(1, "		<link>")
        PrintLine(1, "			<name>F2837xS_Gpio.c</name>")
        PrintLine(1, "			<type>1</type>")
        PrintLine(1, "			<locationURI>PARENT-1-PROJECT_LOC/v140/F2837xS_common/source/F2837xS_Gpio.c</locationURI>")
        PrintLine(1, "		</link>")
        PrintLine(1, "		<link>")
        PrintLine(1, "			<name>F2837xS_Spi.c</name>")
        PrintLine(1, "			<type>1</type>")
        PrintLine(1, "			<locationURI>PARENT-1-PROJECT_LOC/v140/F2837xS_common/source/F2837xS_Spi.c</locationURI>")
        PrintLine(1, "		</link>")
        PrintLine(1, "		<link>")
        PrintLine(1, "			<name>F2837xS_SysCtrl.c</name>")
        PrintLine(1, "			<type>1</type>")
        PrintLine(1, "			<locationURI>PARENT-1-PROJECT_LOC/v140/F2837xS_common/source/F2837xS_SysCtrl.c</locationURI>")
        PrintLine(1, "		</link>")
        PrintLine(1, "		<link>")
        PrintLine(1, "			<name>F2837xS_usDelay.asm</name>")
        PrintLine(1, "			<type>1</type>")
        PrintLine(1, "			<locationURI>PARENT-1-PROJECT_LOC/v140/F2837xS_common/source/F2837xS_usDelay.asm</locationURI>")
        PrintLine(1, "		</link>")
        PrintLine(1, "		<link>")
        PrintLine(1, "			<name>f28377sEqep.c</name>")
        PrintLine(1, "			<type>1</type>")
        PrintLine(1, "			<locationURI>PARENT-1-PROJECT_LOC/f28377sSrc/f28377sEqep.c</locationURI>")
        PrintLine(1, "		</link>")
        PrintLine(1, "		<link>")
        PrintLine(1, "			<name>f28377sADC.c</name>")
        PrintLine(1, "			<type>1</type>")
        PrintLine(1, "			<locationURI>PARENT-1-PROJECT_LOC/f28377sSrc/f28377sADC.c</locationURI>")
        PrintLine(1, "		</link>")
        PrintLine(1, "		<link>")
        PrintLine(1, "			<name>f28377sDAC.c</name>")
        PrintLine(1, "			<type>1</type>")
        PrintLine(1, "			<locationURI>PARENT-1-PROJECT_LOC/f28377sSrc/f28377sDAC.c</locationURI>")
        PrintLine(1, "		</link>")
        PrintLine(1, "		<link>")
        PrintLine(1, "			<name>f28377sEPWM3A.c</name>")
        PrintLine(1, "			<type>1</type>")
        PrintLine(1, "			<locationURI>PARENT-1-PROJECT_LOC/f28377sSrc/f28377sEPWM3A.c</locationURI>")
        PrintLine(1, "		</link>")
        PrintLine(1, "		<link>")
        PrintLine(1, "			<name>" & ProjectName & ".cfg</name>")
        PrintLine(1, "			<type>1</type>")
        PrintLine(1, "			<locationURI>PARENT-1-PROJECT_LOC/" & ProjectName & ".cfg</locationURI>")
        PrintLine(1, "		</link>")
        PrintLine(1, "		<link>")
        PrintLine(1, "			<name>f28377sCoecsl.c</name>")
        PrintLine(1, "			<type>1</type>")
        PrintLine(1, "			<locationURI>PARENT-1-PROJECT_LOC/f28377sSrc/f28377sCoecsl.c</locationURI>")
        PrintLine(1, "		</link>")
        PrintLine(1, "		<link>")
        PrintLine(1, "			<name>f28377sSerial.c</name>")
        PrintLine(1, "			<type>1</type>")
        PrintLine(1, "			<locationURI>PARENT-1-PROJECT_LOC/f28377sSrc/f28377sSerial.c</locationURI>")
        PrintLine(1, "		</link>")
        PrintLine(1, "		<link>")
        PrintLine(1, "			<name>lcd.c</name>")
        PrintLine(1, "			<type>1</type>")
        PrintLine(1, "			<locationURI>PARENT-1-PROJECT_LOC/f28377sSrc/lcd.c</locationURI>")
        PrintLine(1, "		</link>")
        PrintLine(1, "		<link>")
        PrintLine(1, "			<name>user_ " & ProjectName & ".c</name>")
        PrintLine(1, "			<type>1</type>")
        PrintLine(1, "			<locationURI>PARENT-1-PROJECT_LOC/user_" & ProjectName & ".c</locationURI>")
        PrintLine(1, "		</link>")
        PrintLine(1, "	</linkedResources>")
        PrintLine(1, "</projectDescription>")
        PrintLine(1, "")
        FileClose(1)


        FileOpen(1, Project_cproject_fileFullPath, OpenMode.Output)
        PrintLine(1, "<?xml version=""1.0"" encoding=""UTF-8"" standalone=""no""?>")
        PrintLine(1, "<?fileVersion 4.0.0?><cproject storage_type_id=""org.eclipse.cdt.core.XmlProjectDescriptionStorage"">")
        PrintLine(1, "	<storageModule configRelations=""2"" moduleId=""org.eclipse.cdt.core.settings"">")
        PrintLine(1, "		<cconfiguration id=""com.ti.ccstudio.buildDefinitions.C2000.Debug.1376586523"">")
        PrintLine(1, "			<storageModule buildSystemId=""org.eclipse.cdt.managedbuilder.core.configurationDataProvider"" id=""com.ti.ccstudio.buildDefinitions.C2000.Debug.1376586523"" moduleId=""org.eclipse.cdt.core.settings"" name=""Debug"">")
        PrintLine(1, "				<externalSettings/>")
        PrintLine(1, "				<extensions>")
        PrintLine(1, "					<extension id=""com.ti.ccstudio.errorparser.CoffErrorParser"" point=""org.eclipse.cdt.core.ErrorParser""/>")
        PrintLine(1, "					<extension id=""com.ti.ccstudio.errorparser.LinkErrorParser"" point=""org.eclipse.cdt.core.ErrorParser""/>")
        PrintLine(1, "					<extension id=""com.ti.ccstudio.errorparser.AsmErrorParser"" point=""org.eclipse.cdt.core.ErrorParser""/>")
        PrintLine(1, "					<extension id=""org.eclipse.rtsc.xdctools.parsers.ErrorParser"" point=""org.eclipse.cdt.core.ErrorParser""/>")
        PrintLine(1, "					<extension id=""com.ti.ccstudio.binaryparser.CoffParser"" point=""org.eclipse.cdt.core.BinaryParser""/>")
        PrintLine(1, "				</extensions>")
        PrintLine(1, "			</storageModule>")
        PrintLine(1, "			<storageModule moduleId=""cdtBuildSystem"" version=""4.0.0"">")
        PrintLine(1, "				<configuration artifactExtension=""out"" artifactName=""${ProjName}"" buildProperties="""" cleanCommand=""${CG_CLEAN_CMD}"" description="""" errorParsers=""org.eclipse.rtsc.xdctools.parsers.ErrorParser;com.ti.ccstudio.errorparser.CoffErrorParser;com.ti.ccstudio.errorparser.LinkErrorParser;com.ti.ccstudio.errorparser.AsmErrorParser"" id=""com.ti.ccstudio.buildDefinitions.C2000.Debug.1376586523"" name=""Debug"" parent=""com.ti.ccstudio.buildDefinitions.C2000.Debug"" postbuildStep="""" prebuildStep="""">")
        PrintLine(1, "					<folderInfo id=""com.ti.ccstudio.buildDefinitions.C2000.Debug.1376586523."" name=""/"" resourcePath="""">")
        PrintLine(1, "						<toolChain id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.exe.DebugToolchain.593365834"" name=""TI Build Tools"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.exe.DebugToolchain"" targetTool=""com.ti.ccstudio.buildDefinitions.C2000_17.6.exe.linkerDebug.957484707"">")
        PrintLine(1, "							<option id=""com.ti.ccstudio.buildDefinitions.core.OPT_TAGS.624468742"" superClass=""com.ti.ccstudio.buildDefinitions.core.OPT_TAGS"" valueType=""stringList"">")
        PrintLine(1, "								<listOptionValue builtIn=""false"" value=""DEVICE_CONFIGURATION_ID=TMS320C28XX.TMS320F28377S""/>")
        PrintLine(1, "								<listOptionValue builtIn=""false"" value=""OUTPUT_FORMAT=COFF""/>")
        PrintLine(1, "								<listOptionValue builtIn=""false"" value=""CCS_MBS_VERSION=6.1.3""/>")
        PrintLine(1, "								<listOptionValue builtIn=""false"" value=""LINKER_COMMAND_FILE=""/>")
        PrintLine(1, "								<listOptionValue builtIn=""false"" value=""RUNTIME_SUPPORT_LIBRARY=libc.a""/>")
        PrintLine(1, "								<listOptionValue builtIn=""false"" value=""RTSC_MBS_VERSION=2.2.0""/>")
        PrintLine(1, "								<listOptionValue builtIn=""false"" value=""XDC_VERSION=3.32.0.06_core""/>")
        PrintLine(1, "								<listOptionValue builtIn=""false"" value=""RTSC_PRODUCTS=com.ti.rtsc.SYSBIOS:6.51.0.15;com.ti.rtsc.TIRTOSc2000:2.16.1.14;""/>")
        PrintLine(1, "								<listOptionValue builtIn=""false"" value=""INACTIVE_REPOS=${COM_TI_RTSC_TIRTOSC2000_INSTALL_DIR}/products/bios_6_45_02_31/packages;${COM_TI_RTSC_TIRTOSC2000_INSTALL_DIR}/products/ndk_2_25_00_09/packages;${TARGET_CONTENT_BASE};""/>")
        PrintLine(1, "								<listOptionValue builtIn=""false"" value=""EXPANDED_REPOS=""/>")
        PrintLine(1, "								<listOptionValue builtIn=""false"" value=""OUTPUT_TYPE=rtscApplication:executable""/>")
        PrintLine(1, "							</option>")
        PrintLine(1, "							<option id=""com.ti.ccstudio.buildDefinitions.core.OPT_CODEGEN_VERSION.277214038"" superClass=""com.ti.ccstudio.buildDefinitions.core.OPT_CODEGEN_VERSION"" value=""17.6.0.STS"" valueType=""string""/>")
        PrintLine(1, "							<targetPlatform id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.exe.targetPlatformDebug.1470728200"" name=""Platform"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.exe.targetPlatformDebug""/>")
        PrintLine(1, "							<builder buildPath=""${BuildDirectory}"" id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.exe.builderDebug.1944606057"" name=""GNU Make.Debug"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.exe.builderDebug""/>")
        PrintLine(1, "							<tool id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.exe.compilerDebug.1850127733"" name=""C2000 Compiler"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.exe.compilerDebug"">")
        PrintLine(1, "								<option id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.LARGE_MEMORY_MODEL.1851100204"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.LARGE_MEMORY_MODEL"" value=""true"" valueType=""boolean""/>")
        PrintLine(1, "								<option id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.UNIFIED_MEMORY.115063364"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.UNIFIED_MEMORY"" value=""true"" valueType=""boolean""/>")
        PrintLine(1, "								<option id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.SILICON_VERSION.559581391"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.SILICON_VERSION"" value=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.SILICON_VERSION.28"" valueType=""enumerated""/>")
        PrintLine(1, "								<option id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.FLOAT_SUPPORT.763893628"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.FLOAT_SUPPORT"" value=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.FLOAT_SUPPORT.fpu32"" valueType=""enumerated""/>")
        PrintLine(1, "								<option id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.CLA_SUPPORT.1759374793"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.CLA_SUPPORT"" value=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.CLA_SUPPORT.cla1"" valueType=""enumerated""/>")
        PrintLine(1, "								<option id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.VCU_SUPPORT.512927635"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.VCU_SUPPORT"" value=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.VCU_SUPPORT.vcu2"" valueType=""enumerated""/>")
        PrintLine(1, "								<option id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.TMU_SUPPORT.2113980487"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.TMU_SUPPORT"" value=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.TMU_SUPPORT.tmu0"" valueType=""enumerated""/>")
        PrintLine(1, "								<option id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.INCLUDE_PATH.981293865"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.INCLUDE_PATH"" valueType=""includePath"">")
        PrintLine(1, "									<listOptionValue builtIn=""false"" value=""&quot;${CG_TOOL_ROOT}/include&quot;""/>")
        PrintLine(1, "									<listOptionValue builtIn=""false"" value=""&quot;" & Project_f28377sHeadersDir & "&quot;""/>")
        PrintLine(1, "									<listOptionValue builtIn=""false"" value=""&quot;" & Project_DSP28377_common_include_Dir & "&quot;""/>")
        PrintLine(1, "									<listOptionValue builtIn=""false"" value=""&quot;" & Project_DSP28377_headers_include_Dir & "&quot;""/>")
        PrintLine(1, "								</option>")
        PrintLine(1, "								<option id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.DEBUGGING_MODEL.1236610135"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.DEBUGGING_MODEL"" value=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.DEBUGGING_MODEL.SYMDEBUG__DWARF"" valueType=""enumerated""/>")
        PrintLine(1, "								<option id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.DEFINE.1665873757"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.DEFINE"" valueType=""definedSymbols"">")
        PrintLine(1, "									<listOptionValue builtIn=""false"" value=""_FLASH""/>")
        PrintLine(1, "									<listOptionValue builtIn=""false"" value=""CPU1""/>")
        PrintLine(1, "								</option>")
        PrintLine(1, "								<option id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.DIAG_WARNING.825132237"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.DIAG_WARNING"" valueType=""stringList"">")
        PrintLine(1, "									<listOptionValue builtIn=""false"" value=""225""/>")
        PrintLine(1, "								</option>")
        PrintLine(1, "								<option id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.DISPLAY_ERROR_NUMBER.1826855765"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.DISPLAY_ERROR_NUMBER"" value=""true"" valueType=""boolean""/>")
        PrintLine(1, "								<option id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.DIAG_SUPPRESS.531600435"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.DIAG_SUPPRESS"" valueType=""stringList"">")
        PrintLine(1, "									<listOptionValue builtIn=""false"" value=""1311""/>")
        PrintLine(1, "								</option>")
        PrintLine(1, "								<option id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.DIAG_WRAP.1002695146"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.DIAG_WRAP"" value=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.DIAG_WRAP.off"" valueType=""enumerated""/>")
        PrintLine(1, "								<inputType id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compiler.inputType__C_SRCS.1463775731"" name=""C Sources"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compiler.inputType__C_SRCS""/>")
        PrintLine(1, "								<inputType id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compiler.inputType__CPP_SRCS.344986764"" name=""C++ Sources"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compiler.inputType__CPP_SRCS""/>")
        PrintLine(1, "								<inputType id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compiler.inputType__ASM_SRCS.819442585"" name=""Assembly Sources"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compiler.inputType__ASM_SRCS""/>")
        PrintLine(1, "								<inputType id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compiler.inputType__ASM2_SRCS.1932379146"" name=""Assembly Sources"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compiler.inputType__ASM2_SRCS""/>")
        PrintLine(1, "							</tool>")
        PrintLine(1, "							<tool id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.exe.linkerDebug.957484707"" name=""C2000 Linker"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.exe.linkerDebug"">")
        PrintLine(1, "								<option id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.linkerID.STACK_SIZE.506300687"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.linkerID.STACK_SIZE"" value=""0x200"" valueType=""string""/>")
        PrintLine(1, "								<option id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.linkerID.OUTPUT_FILE.1794707011"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.linkerID.OUTPUT_FILE"" value=""&quot;${ProjName}.out&quot;"" valueType=""string""/>")
        PrintLine(1, "								<option id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.linkerID.MAP_FILE.1707435941"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.linkerID.MAP_FILE"" value=""&quot;${ProjName}.map&quot;"" valueType=""string""/>")
        PrintLine(1, "								<option id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.linkerID.LIBRARY.1930600080"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.linkerID.LIBRARY"" valueType=""libs"">")
        PrintLine(1, "									<listOptionValue builtIn=""false"" value=""&quot;libc.a&quot;""/>")
        PrintLine(1, "									<listOptionValue builtIn=""false"" value=""&quot;${CG_TOOL_ROOT}\lib\rts2800_fpu32.lib&quot;""/>")
        PrintLine(1, "									<listOptionValue builtIn=""false"" value=""&quot;" & Project_DSP28377_common_cmd_Dir & "2837x_Dan_FLASH_lnk_cpu1.cmd&quot;""/>")
        PrintLine(1, "									<listOptionValue builtIn=""false"" value=""&quot;" & Project_DSP28377_headers_cmd_Dir & "F2837xS_Headers_BIOS.cmd&quot;""/>")
        PrintLine(1, "								</option>")
        PrintLine(1, "								<option id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.linkerID.SEARCH_PATH.1630267051"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.linkerID.SEARCH_PATH"" valueType=""libPaths"">")
        PrintLine(1, "									<listOptionValue builtIn=""false"" value=""&quot;${CG_TOOL_ROOT}/lib&quot;""/>")
        PrintLine(1, "									<listOptionValue builtIn=""false"" value=""&quot;" & Project_DSP28377_common_cmd_Dir & "&quot;""/>")
        PrintLine(1, "									<listOptionValue builtIn=""false"" value=""&quot;" & Project_DSP28377_headers_cmd_Dir & "&quot;""/>")
        PrintLine(1, "									<listOptionValue builtIn=""false"" value=""&quot;${CG_TOOL_ROOT}/include&quot;""/>")
        PrintLine(1, "								</option>")
        PrintLine(1, "								<option id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.linkerID.DISPLAY_ERROR_NUMBER.1925780962"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.linkerID.DISPLAY_ERROR_NUMBER"" value=""true"" valueType=""boolean""/>")
        PrintLine(1, "								<option id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.linkerID.DIAG_WRAP.594690708"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.linkerID.DIAG_WRAP"" value=""com.ti.ccstudio.buildDefinitions.C2000_17.6.linkerID.DIAG_WRAP.off"" valueType=""enumerated""/>")
        PrintLine(1, "								<option id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.linkerID.XML_LINK_INFO.1612587029"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.linkerID.XML_LINK_INFO"" value=""&quot;${ProjName}_linkInfo.xml&quot;"" valueType=""string""/>")
        PrintLine(1, "								<inputType id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.exeLinker.inputType__CMD_SRCS.963392306"" name=""Linker Command Files"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.exeLinker.inputType__CMD_SRCS""/>")
        PrintLine(1, "								<inputType id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.exeLinker.inputType__CMD2_SRCS.366155911"" name=""Linker Command Files"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.exeLinker.inputType__CMD2_SRCS""/>")
        PrintLine(1, "								<inputType id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.exeLinker.inputType__GEN_CMDS.1345298400"" name=""Generated Linker Command Files"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.exeLinker.inputType__GEN_CMDS""/>")
        PrintLine(1, "							</tool>")
        PrintLine(1, "							<tool id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.hex.1272998190"" name=""C2000 Hex Utility"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.hex""/>")
        PrintLine(1, "							<tool id=""com.ti.rtsc.buildDefinitions.XDC_3.16.tool.1197431112"" name=""XDCtools"" superClass=""com.ti.rtsc.buildDefinitions.XDC_3.16.tool"">")
        PrintLine(1, "								<option id=""com.ti.rtsc.buildDefinitions.XDC_3.16.tool.XDC_PATH.63194795"" superClass=""com.ti.rtsc.buildDefinitions.XDC_3.16.tool.XDC_PATH"" valueType=""stringList"">")
        PrintLine(1, "									<listOptionValue builtIn=""false"" value=""${COM_TI_RTSC_TIRTOSC2000_REPOS}""/>")
        PrintLine(1, "									<listOptionValue builtIn=""false"" value=""${BIOS_CG_ROOT}/packages""/>")
        PrintLine(1, "								</option>")
        PrintLine(1, "								<option id=""com.ti.rtsc.buildDefinitions.XDC_3.16.tool.TARGET.631589153"" superClass=""com.ti.rtsc.buildDefinitions.XDC_3.16.tool.TARGET"" value=""ti.targets.C28_float"" valueType=""string""/>")
        PrintLine(1, "								<option id=""com.ti.rtsc.buildDefinitions.XDC_3.16.tool.PLATFORM.804382714"" superClass=""com.ti.rtsc.buildDefinitions.XDC_3.16.tool.PLATFORM"" value=""ti.platforms.tms320x28:TMS320F28377S"" valueType=""string""/>")
        PrintLine(1, "								<option id=""com.ti.rtsc.buildDefinitions.XDC_3.16.tool.PLATFORM_RAW.853952713"" superClass=""com.ti.rtsc.buildDefinitions.XDC_3.16.tool.PLATFORM_RAW"" value=""ti.platforms.tms320x28:TMS320F28377S"" valueType=""string""/>")
        PrintLine(1, "								<option id=""com.ti.rtsc.buildDefinitions.XDC_3.16.tool.BUILD_PROFILE.676529676"" superClass=""com.ti.rtsc.buildDefinitions.XDC_3.16.tool.BUILD_PROFILE"" value=""debug"" valueType=""string""/>")
        PrintLine(1, "								<option id=""com.ti.rtsc.buildDefinitions.XDC_3.16.tool.CODEGEN_TOOL_DIR.684392737"" superClass=""com.ti.rtsc.buildDefinitions.XDC_3.16.tool.CODEGEN_TOOL_DIR"" value=""&quot;${CG_TOOL_ROOT}&quot;"" valueType=""string""/>")
        PrintLine(1, "							</tool>")
        PrintLine(1, "						</toolChain>")
        PrintLine(1, "					</folderInfo>")
        PrintLine(1, "					<sourceEntries>")
        PrintLine(1, "						<entry excluding=""28377S_FLASH_lnk.cmd"" flags=""VALUE_WORKSPACE_PATH|RESOLVED"" kind=""sourcePath"" name=""""/>")
        PrintLine(1, "					</sourceEntries>")
        PrintLine(1, "				</configuration>")
        PrintLine(1, "			</storageModule>")
        PrintLine(1, "			<storageModule moduleId=""org.eclipse.cdt.core.externalSettings""/>")
        PrintLine(1, "		</cconfiguration>")
        PrintLine(1, "		<cconfiguration id=""com.ti.ccstudio.buildDefinitions.C2000.Release.2143738011"">")
        PrintLine(1, "			<storageModule buildSystemId=""org.eclipse.cdt.managedbuilder.core.configurationDataProvider"" id=""com.ti.ccstudio.buildDefinitions.C2000.Release.2143738011"" moduleId=""org.eclipse.cdt.core.settings"" name=""Release"">")
        PrintLine(1, "				<externalSettings/>")
        PrintLine(1, "				<extensions>")
        PrintLine(1, "					<extension id=""com.ti.ccstudio.errorparser.CoffErrorParser"" point=""org.eclipse.cdt.core.ErrorParser""/>")
        PrintLine(1, "					<extension id=""com.ti.ccstudio.errorparser.LinkErrorParser"" point=""org.eclipse.cdt.core.ErrorParser""/>")
        PrintLine(1, "					<extension id=""com.ti.ccstudio.errorparser.AsmErrorParser"" point=""org.eclipse.cdt.core.ErrorParser""/>")
        PrintLine(1, "					<extension id=""org.eclipse.rtsc.xdctools.parsers.ErrorParser"" point=""org.eclipse.cdt.core.ErrorParser""/>")
        PrintLine(1, "					<extension id=""com.ti.ccstudio.binaryparser.CoffParser"" point=""org.eclipse.cdt.core.BinaryParser""/>")
        PrintLine(1, "				</extensions>")
        PrintLine(1, "			</storageModule>")
        PrintLine(1, "			<storageModule moduleId=""cdtBuildSystem"" version=""4.0.0"">")
        PrintLine(1, "				<configuration artifactExtension=""out"" artifactName=""${ProjName}"" buildProperties="""" cleanCommand=""${CG_CLEAN_CMD}"" description="""" errorParsers=""org.eclipse.rtsc.xdctools.parsers.ErrorParser;com.ti.ccstudio.errorparser.CoffErrorParser;com.ti.ccstudio.errorparser.LinkErrorParser;com.ti.ccstudio.errorparser.AsmErrorParser"" id=""com.ti.ccstudio.buildDefinitions.C2000.Release.2143738011"" name=""Release"" parent=""com.ti.ccstudio.buildDefinitions.C2000.Release"" postbuildStep="""" prebuildStep="""">")
        PrintLine(1, "					<folderInfo id=""com.ti.ccstudio.buildDefinitions.C2000.Release.2143738011."" name=""/"" resourcePath="""">")
        PrintLine(1, "						<toolChain id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.exe.ReleaseToolchain.1033881015"" name=""TI Build Tools"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.exe.ReleaseToolchain"" targetTool=""com.ti.ccstudio.buildDefinitions.C2000_17.6.exe.linkerRelease.2028776337"">")
        PrintLine(1, "							<option id=""com.ti.ccstudio.buildDefinitions.core.OPT_TAGS.1920818564"" superClass=""com.ti.ccstudio.buildDefinitions.core.OPT_TAGS"" valueType=""stringList"">")
        PrintLine(1, "								<listOptionValue builtIn=""false"" value=""DEVICE_CONFIGURATION_ID=TMS320C28XX.TMS320F28377S""/>")
        PrintLine(1, "								<listOptionValue builtIn=""false"" value=""OUTPUT_FORMAT=COFF""/>")
        PrintLine(1, "								<listOptionValue builtIn=""false"" value=""CCS_MBS_VERSION=5.5.0""/>")
        PrintLine(1, "								<listOptionValue builtIn=""false"" value=""LINKER_COMMAND_FILE=28377S_FLASH_lnk.cmd""/>")
        PrintLine(1, "								<listOptionValue builtIn=""false"" value=""RUNTIME_SUPPORT_LIBRARY=libc.a""/>")
        PrintLine(1, "								<listOptionValue builtIn=""false"" value=""RTSC_MBS_VERSION=2.2.0""/>")
        PrintLine(1, "								<listOptionValue builtIn=""false"" value=""XDC_VERSION=3.30.5.60_core""/>")
        PrintLine(1, "								<listOptionValue builtIn=""false"" value=""RTSC_PRODUCTS=com.ti.mcu.msp430.driverlib:1.90.0.65;com.ti.mcu.msp430ware:1.90.0.30;com.ti.rtsc.TIRTOSc2000:2.10.1.38;""/>")
        PrintLine(1, "								<listOptionValue builtIn=""false"" value=""OUTPUT_TYPE=executable""/>")
        PrintLine(1, "							</option>")
        PrintLine(1, "							<option id=""com.ti.ccstudio.buildDefinitions.core.OPT_CODEGEN_VERSION.359698171"" name=""Compiler version"" superClass=""com.ti.ccstudio.buildDefinitions.core.OPT_CODEGEN_VERSION"" value=""17.6.0.STS"" valueType=""string""/>")
        PrintLine(1, "							<targetPlatform id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.exe.targetPlatformRelease.1592518039"" name=""Platform"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.exe.targetPlatformRelease""/>")
        PrintLine(1, "							<builder buildPath=""${BuildDirectory}"" id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.exe.builderRelease.2020553903"" keepEnvironmentInBuildfile=""false"" name=""GNU Make"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.exe.builderRelease""/>")
        PrintLine(1, "							<tool id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.exe.compilerRelease.172997450"" name=""C2000 Compiler"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.exe.compilerRelease"">")
        PrintLine(1, "								<option id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.LARGE_MEMORY_MODEL.242354729"" name=""Use large memory model (--large_memory_model, -ml)"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.LARGE_MEMORY_MODEL"" value=""true"" valueType=""boolean""/>")
        PrintLine(1, "								<option id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.UNIFIED_MEMORY.1423348279"" name=""Unified memory (--unified_memory, -mt)"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.UNIFIED_MEMORY"" value=""true"" valueType=""boolean""/>")
        PrintLine(1, "								<option id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.SILICON_VERSION.924796817"" name=""Processor version (--silicon_version, -v)"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.SILICON_VERSION"" value=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.SILICON_VERSION.28"" valueType=""enumerated""/>")
        PrintLine(1, "								<option id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.FLOAT_SUPPORT.1933985171"" name=""Specify floating point support (--float_support)"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.FLOAT_SUPPORT"" value=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.FLOAT_SUPPORT.fpu32"" valueType=""enumerated""/>")
        PrintLine(1, "								<option id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.CLA_SUPPORT.426933073"" name=""Specify CLA support (--cla_support)"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.CLA_SUPPORT"" value=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.CLA_SUPPORT.cla1"" valueType=""enumerated""/>")
        PrintLine(1, "								<option id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.VCU_SUPPORT.2125875205"" name=""Specify VCU support (--vcu_support)"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.VCU_SUPPORT"" value=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.VCU_SUPPORT.vcu2"" valueType=""enumerated""/>")
        PrintLine(1, "								<option id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.TMU_SUPPORT.209889384"" name=""Specify TMU support (--tmu_support)"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.TMU_SUPPORT"" value=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.TMU_SUPPORT.tmu0"" valueType=""enumerated""/>")
        PrintLine(1, "								<option id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.INCLUDE_PATH.1691589612"" name=""Add dir to #include search path (--include_path, -I)"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.INCLUDE_PATH"" valueType=""includePath"">")
        PrintLine(1, "									<listOptionValue builtIn=""false"" value=""&quot;${CG_TOOL_ROOT}/include&quot;""/>")
        PrintLine(1, "								</option>")
        PrintLine(1, "								<option id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.DIAG_WARNING.492786288"" name=""Treat diagnostic &lt;id&gt; as warning (--diag_warning, -pdsw)"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.DIAG_WARNING"" valueType=""stringList"">")
        PrintLine(1, "									<listOptionValue builtIn=""false"" value=""225""/>")
        PrintLine(1, "								</option>")
        PrintLine(1, "								<option id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.DISPLAY_ERROR_NUMBER.496050519"" name=""Emit diagnostic identifier numbers (--display_error_number, -pden)"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.DISPLAY_ERROR_NUMBER"" value=""true"" valueType=""boolean""/>")
        PrintLine(1, "								<option id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.DIAG_WRAP.889709515"" name=""Wrap diagnostic messages (--diag_wrap)"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.DIAG_WRAP"" value=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compilerID.DIAG_WRAP.off"" valueType=""enumerated""/>")
        PrintLine(1, "								<inputType id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compiler.inputType__C_SRCS.926616066"" name=""C Sources"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compiler.inputType__C_SRCS""/>")
        PrintLine(1, "								<inputType id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compiler.inputType__CPP_SRCS.424472719"" name=""C++ Sources"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compiler.inputType__CPP_SRCS""/>")
        PrintLine(1, "								<inputType id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compiler.inputType__ASM_SRCS.1692680878"" name=""Assembly Sources"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compiler.inputType__ASM_SRCS""/>")
        PrintLine(1, "								<inputType id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compiler.inputType__ASM2_SRCS.1285733609"" name=""Assembly Sources"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.compiler.inputType__ASM2_SRCS""/>")
        PrintLine(1, "							</tool>")
        PrintLine(1, "							<tool id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.exe.linkerRelease.2028776337"" name=""C2000 Linker"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.exe.linkerRelease"">")
        PrintLine(1, "								<option id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.linkerID.STACK_SIZE.718379208"" name=""Set C system stack size (--stack_size, -stack)"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.linkerID.STACK_SIZE"" value=""0x200"" valueType=""string""/>")
        PrintLine(1, "								<option id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.linkerID.OUTPUT_FILE.1484342568"" name=""Specify output file name (--output_file, -o)"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.linkerID.OUTPUT_FILE"" value=""&quot;${ProjName}.out&quot;"" valueType=""string""/>")
        PrintLine(1, "								<option id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.linkerID.MAP_FILE.2082395617"" name=""Input and output sections listed into &lt;file&gt; (--map_file, -m)"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.linkerID.MAP_FILE"" value=""&quot;${ProjName}.map&quot;"" valueType=""string""/>")
        PrintLine(1, "								<option id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.linkerID.SEARCH_PATH.849744578"" name=""Add &lt;dir&gt; to library search path (--search_path, -i)"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.linkerID.SEARCH_PATH"" valueType=""libPaths"">")
        PrintLine(1, "									<listOptionValue builtIn=""false"" value=""&quot;${CG_TOOL_ROOT}/lib&quot;""/>")
        PrintLine(1, "									<listOptionValue builtIn=""false"" value=""&quot;${CG_TOOL_ROOT}/include&quot;""/>")
        PrintLine(1, "								</option>")
        PrintLine(1, "								<option id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.linkerID.DISPLAY_ERROR_NUMBER.1224766987"" name=""Emit diagnostic identifier numbers (--display_error_number)"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.linkerID.DISPLAY_ERROR_NUMBER"" value=""true"" valueType=""boolean""/>")
        PrintLine(1, "								<option id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.linkerID.DIAG_WRAP.146678114"" name=""Wrap diagnostic messages (--diag_wrap)"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.linkerID.DIAG_WRAP"" value=""com.ti.ccstudio.buildDefinitions.C2000_17.6.linkerID.DIAG_WRAP.off"" valueType=""enumerated""/>")
        PrintLine(1, "								<option id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.linkerID.XML_LINK_INFO.1265086347"" name=""Detailed link information data-base into &lt;file&gt; (--xml_link_info, -xml_link_info)"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.linkerID.XML_LINK_INFO"" value=""&quot;${ProjName}_linkInfo.xml&quot;"" valueType=""string""/>")
        PrintLine(1, "								<option id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.linkerID.LIBRARY.2001668634"" name=""Include library file or command file as input (--library, -l)"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.linkerID.LIBRARY"" valueType=""libs"">")
        PrintLine(1, "									<listOptionValue builtIn=""false"" value=""&quot;libc.a&quot;""/>")
        PrintLine(1, "								</option>")
        PrintLine(1, "								<inputType id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.exeLinker.inputType__CMD_SRCS.1349709661"" name=""Linker Command Files"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.exeLinker.inputType__CMD_SRCS""/>")
        PrintLine(1, "								<inputType id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.exeLinker.inputType__CMD2_SRCS.1560365127"" name=""Linker Command Files"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.exeLinker.inputType__CMD2_SRCS""/>")
        PrintLine(1, "								<inputType id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.exeLinker.inputType__GEN_CMDS.212340209"" name=""Generated Linker Command Files"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.exeLinker.inputType__GEN_CMDS""/>")
        PrintLine(1, "							</tool>")
        PrintLine(1, "							<tool id=""com.ti.ccstudio.buildDefinitions.C2000_17.6.hex.202358355"" name=""C2000 Hex Utility"" superClass=""com.ti.ccstudio.buildDefinitions.C2000_17.6.hex""/>")
        PrintLine(1, "							<tool id=""com.ti.rtsc.buildDefinitions.XDC_3.16.tool.713630"" name=""XDCtools"" superClass=""com.ti.rtsc.buildDefinitions.XDC_3.16.tool"">")
        PrintLine(1, "								<option id=""com.ti.rtsc.buildDefinitions.XDC_3.16.tool.CODEGEN_TOOL_DIR.984924146"" name=""Compiler tools directory (-c)"" superClass=""com.ti.rtsc.buildDefinitions.XDC_3.16.tool.CODEGEN_TOOL_DIR"" value=""&quot;${CG_TOOL_ROOT}&quot;"" valueType=""string""/>")
        PrintLine(1, "								<option id=""com.ti.rtsc.buildDefinitions.XDC_3.16.tool.TARGET.865331259"" name=""Target (-t)"" superClass=""com.ti.rtsc.buildDefinitions.XDC_3.16.tool.TARGET"" value=""ti.targets.C28_float"" valueType=""string""/>")
        PrintLine(1, "								<option id=""com.ti.rtsc.buildDefinitions.XDC_3.16.tool.BUILD_PROFILE.1725786225"" name=""Build-profile (-r)"" superClass=""com.ti.rtsc.buildDefinitions.XDC_3.16.tool.BUILD_PROFILE"" value=""debug"" valueType=""string""/>")
        PrintLine(1, "								<option id=""com.ti.rtsc.buildDefinitions.XDC_3.16.tool.XDC_PATH.34627119"" name=""Package repositories (--xdcpath)"" superClass=""com.ti.rtsc.buildDefinitions.XDC_3.16.tool.XDC_PATH"" valueType=""stringList"">")
        PrintLine(1, "									<listOptionValue builtIn=""false"" value=""${MSP430_DRIVERLIB_ROOT}/packages""/>")
        PrintLine(1, "									<listOptionValue builtIn=""false"" value=""${MSP430_DRIVERLIB_ROOT}/.""/>")
        PrintLine(1, "									<listOptionValue builtIn=""false"" value=""${COM_TI_MCU_MSP430WARE_INSTALL_DIR}/driverlib/packages""/>")
        PrintLine(1, "									<listOptionValue builtIn=""false"" value=""${COM_TI_RTSC_TIRTOSC2000_INSTALL_DIR}/packages""/>")
        PrintLine(1, "									<listOptionValue builtIn=""false"" value=""${COM_TI_RTSC_TIRTOSC2000_INSTALL_DIR}/products/bios_6_41_04_54/packages""/>")
        PrintLine(1, "									<listOptionValue builtIn=""false"" value=""${COM_TI_RTSC_TIRTOSC2000_INSTALL_DIR}/products/ipc_3_30_01_12/packages""/>")
        PrintLine(1, "									<listOptionValue builtIn=""false"" value=""${COM_TI_RTSC_TIRTOSC2000_INSTALL_DIR}/products/ndk_2_24_02_31/packages""/>")
        PrintLine(1, "									<listOptionValue builtIn=""false"" value=""${COM_TI_RTSC_TIRTOSC2000_INSTALL_DIR}/products/uia_2_00_02_39/packages""/>")
        PrintLine(1, "									<listOptionValue builtIn=""false"" value=""${TARGET_CONTENT_BASE}""/>")
        PrintLine(1, "								</option>")
        PrintLine(1, "							</tool>")
        PrintLine(1, "						</toolChain>")
        PrintLine(1, "					</folderInfo>")
        PrintLine(1, "				</configuration>")
        PrintLine(1, "			</storageModule>")
        PrintLine(1, "			<storageModule moduleId=""org.eclipse.cdt.core.externalSettings""/>")
        PrintLine(1, "		</cconfiguration>")
        PrintLine(1, "	</storageModule>")
        PrintLine(1, "	<storageModule moduleId=""org.eclipse.cdt.core.LanguageSettingsProviders""/>")
        PrintLine(1, "	<storageModule moduleId=""cdtBuildSystem"" version=""4.0.0"">")
        PrintLine(1, "		<project id=""" & ProjectName & ".com.ti.ccstudio.buildDefinitions.C2000.ProjectType.868728086"" name=""C2000"" projectType=""com.ti.ccstudio.buildDefinitions.C2000.ProjectType""/>")
        PrintLine(1, "	</storageModule>")
        PrintLine(1, "	<storageModule moduleId=""scannerConfiguration""/>")
        PrintLine(1, "	<storageModule moduleId=""org.eclipse.cdt.core.language.mapping"">")
        PrintLine(1, "		<project-mappings>")
        PrintLine(1, "			<content-type-mapping configuration="""" content-type=""org.eclipse.cdt.core.asmSource"" language=""com.ti.ccstudio.core.TIASMLanguage""/>")
        PrintLine(1, "			<content-type-mapping configuration="""" content-type=""org.eclipse.cdt.core.cHeader"" language=""com.ti.ccstudio.core.TIGCCLanguage""/>")
        PrintLine(1, "			<content-type-mapping configuration="""" content-type=""org.eclipse.cdt.core.cSource"" language=""com.ti.ccstudio.core.TIGCCLanguage""/>")
        PrintLine(1, "			<content-type-mapping configuration="""" content-type=""org.eclipse.cdt.core.cxxHeader"" language=""com.ti.ccstudio.core.TIGPPLanguage""/>")
        PrintLine(1, "			<content-type-mapping configuration="""" content-type=""org.eclipse.cdt.core.cxxSource"" language=""com.ti.ccstudio.core.TIGPPLanguage""/>")
        PrintLine(1, "		</project-mappings>")
        PrintLine(1, "	</storageModule>")
        PrintLine(1, "	<storageModule moduleId=""null.endianPreference""/>")
        PrintLine(1, "	<storageModule moduleId=""cpuFamily""/>")
        PrintLine(1, "</cproject>")
        PrintLine(1, "")

        FileClose(1)

        FileOpen(1, Project_ccsproject_fileFullPath, OpenMode.Output)
        PrintLine(1, "<?xml version=""1.0"" encoding=""UTF-8"" ?>")
        PrintLine(1, "<?ccsproject version=""1.0""?>")
        PrintLine(1, "<projectOptions>")
        PrintLine(1, "      <deviceVariant value=""TMS320C28XX.TMS320F28377S""/>")
        PrintLine(1, "      <deviceFamily value=""C2000""/>")
        PrintLine(1, "      <codegenToolVersion value=""17.6.0.STS""/>")
        PrintLine(1, "      <isElfFormat value=""false""/>")
        PrintLine(1, "      <rts value=""libc.a""/>")
        PrintLine(1, "      <createSlaveProjects value=""""/>")
        PrintLine(1, "      <templateProperties value=""id=com.ti.common.project.core.emptyProjectWithMainTemplate,""/>")
        PrintLine(1, "      <isTargetManual value=""false""/>")
        PrintLine(1, "      <connection value=""common/targetdb/connections/SD510USB_Connection.xml""/>")
        PrintLine(1, "</projectOptions>")
        PrintLine(1, "")

        FileClose(1)

        FileOpen(1, Matlab_funcGE420_serialread_fileFullPath, OpenMode.Output)

        PrintLine(1, "function [out3] = GE420_serialread(name,varsize,comport)")
        PrintLine(1, "%GE420_SERIALREAD")
        PrintLine(1, "%   N = GE420_serialread(NAME,VARSIZE,COMPORT) will return data from the DSP declared")
        PrintLine(1, "%	in either the "".my_arrs"" or "".my_vars"" data sections where NAME refers to")
        PrintLine(1, "%	the name of the variable or array on the DSP, and varsize refers to the")
        PrintLine(1, "%	size (number of 32-bit words) in the variable or array.")
        PrintLine(1, "%   comport is a string with the COM port connected to the ""USB Serial Port"".")
        PrintLine(1, "%	It is usually the largest number of COM port in your system.  If you do not")
        PrintLine(1, "%	know your comport, run the command ""list_serailports"" to see all the")
        PrintLine(1, "%	available comports.")
        PrintLine(1, "%")
        PrintLine(1, "%	For example, to read the float variable ""myfloat"" from the DSP and store")
        PrintLine(1, "%	it into a Matlab single variable called ""mydata"" you would type:")
        PrintLine(1, "%")
        PrintLine(1, "%		mydata = GE420_serialread('myfloat',1,'COM12');")
        PrintLine(1, "%")
        PrintLine(1, "%	To read the first 1000 entries in the float array ""myfloatarray"" ")
        PrintLine(1, "%	and store it into a Matlab single variable array called ""myarray"" ")
        PrintLine(1, "%	you would type:	")
        PrintLine(1, "%")
        PrintLine(1, "%		myarray = GE420_serialread('myfloatarray',1000,'COM12');")
        PrintLine(1, "%")
        PrintLine(1, "")
        PrintLine(1, "")
        PrintLine(1, "if (varsize > 1000)")
        PrintLine(1, "    display('Varsize must be 1000 or less');")
        PrintLine(1, "    exception = MException('MATLAB:VarsizeMAX','Varsize must be 1000 or smaller');")
        PrintLine(1, "    throw(exception);")
        PrintLine(1, "end")
        PrintLine(1, "")
        PrintLine(1, "s = instrfind;")
        PrintLine(1, "if length(s) > 0")
        PrintLine(1, "    fclose(s);")
        PrintLine(1, "end")
        PrintLine(1, "clear s;")
        PrintLine(1, "")
        PrintLine(1, "filename = dir('../" & ProjectName & "Project/debug/*.map');")
        PrintLine(1, "")
        PrintLine(1, "map = parseMap(strcat('../" & ProjectName & "Project/debug/',filename.name))")
        PrintLine(1, "")
        PrintLine(1, "memloc = 0;")
        PrintLine(1, "arrsize = size(map);")
        PrintLine(1, "found = 1;")
        PrintLine(1, "")
        PrintLine(1, "for i=1:arrsize(1)")
        PrintLine(1, "    if strfind(char(map(i,1)),name)")
        PrintLine(1, "        memloc = char(map(i,2));")
        PrintLine(1, "        found = 0;")
        PrintLine(1, "    end")
        PrintLine(1, "end")
        PrintLine(1, "if (found == 1)")
        PrintLine(1, "    exception = MException('MATLAB:VarNotFound','Variable name not found.');")
        PrintLine(1, "    throw(exception);")
        PrintLine(1, "end")
        PrintLine(1, "")
        PrintLine(1, "if (testifcom(comport) == 0)")
        PrintLine(1, "    display('Choose from the following COM ports');")
        PrintLine(1, "        list_serialports()")
        PrintLine(1, "    exception = MException('MATLAB:ComportNotFound','COM Port not found.');")
        PrintLine(1, "    throw(exception);")
        PrintLine(1, "end")
        PrintLine(1, "")
        PrintLine(1, "")
        PrintLine(1, "hexsize = dec2hex(varsize,4);")
        PrintLine(1, "hex_str = '2A0932'; % header")
        PrintLine(1, "hex_str = strcat(hex_str,memloc,hexsize);")
        PrintLine(1, "char_str = char(sscanf(hex_str,'%2X').');")
        PrintLine(1, "")
        PrintLine(1, "s = serial(comport);")
        PrintLine(1, "set(s,'BaudRate',115200);")
        PrintLine(1, "s.InputBufferSize = 15000;")
        PrintLine(1, "fopen(s);")
        PrintLine(1, "fwrite(s,char_str);")
        PrintLine(1, "")
        PrintLine(1, "count = 0;")
        PrintLine(1, "while 1")
        PrintLine(1, "    inchar = fread(s,1);")
        PrintLine(1, "    if inchar == 42")
        PrintLine(1, "        inchar = fread(s,1);")
        PrintLine(1, "        inchar = fread(s,1);")
        PrintLine(1, "        if inchar == 51")
        PrintLine(1, "            out3 = fread(s,varsize,'float32');")
        PrintLine(1, "            break;")
        PrintLine(1, "        end")
        PrintLine(1, "    end")
        PrintLine(1, "    count = count + 1;")
        PrintLine(1, "    if count > 100")
        PrintLine(1, "        break;")
        PrintLine(1, "    end")
        PrintLine(1, "end")
        PrintLine(1, "")
        PrintLine(1, "fclose(s)")
        PrintLine(1, "delete(s)")
        PrintLine(1, "clear s")

        FileClose(1)


        FileOpen(1, Matlab_funcGE420_serialread_address_fileFullPath, OpenMode.Output)

        PrintLine(1, "function [out3] = GE420_serialread_address(address,varsize)")
        PrintLine(1, "%GE420_SERIALREAD_ADDRESS")
        PrintLine(1, "%   N = GE420_serialread_address(ADDRESS,VARSIZE) will return data from the")
        PrintLine(1, "%   DSP stored at the location ADDRESS in decimal, not hex, and varsize ")
        PrintLine(1, "%   refers to the size (number of 32-bit words) in the variable or array.")
        PrintLine(1, "%")
        PrintLine(1, "%	For example, to read the float variable at the memory address ")
        PrintLine(1, "%   ""0001f5b0"" on the DSP and store it into a Matlab single variable called")
        PrintLine(1, "%   ""mydata"" you would type:")
        PrintLine(1, "%")
        PrintLine(1, "%		mydata = GE420_serialread_address(128432,1);")
        PrintLine(1, "%")
        PrintLine(1, "%	To read the first 1000 entries in the float array starting at address ")
        PrintLine(1, "%   ""0001f5b0"" and store it into a Matlab single variable array called ")
        PrintLine(1, "%   ""myarray"" you would type:	")
        PrintLine(1, "%")
        PrintLine(1, "%		myarray = GE420_serialread('myfloatarray',1000);")
        PrintLine(1, "%")
        PrintLine(1, "")
        PrintLine(1, "s = instrfind;")
        PrintLine(1, "if length(s) > 0")
        PrintLine(1, "    fclose(s);")
        PrintLine(1, "end")
        PrintLine(1, "clear s;")
        PrintLine(1, "")
        PrintLine(1, "filename = dir('../" & ProjectName & "Project/debug/*.map');")
        PrintLine(1, "")
        PrintLine(1, "map = parseMap(strcat('../" & ProjectName & "Project/debug/',filename.name))")
        PrintLine(1, "")
        PrintLine(1, "memloc = dec2hex(address,8);")
        PrintLine(1, "")
        PrintLine(1, "hexsize = dec2hex(varsize,4);")
        PrintLine(1, "hex_str = '2A0932'; % header")
        PrintLine(1, "hex_str = strcat(hex_str,memloc,hexsize);")
        PrintLine(1, "char_str = char(sscanf(hex_str,'%2X').');")
        PrintLine(1, "")
        PrintLine(1, "s = serial('COM1');")
        PrintLine(1, "set(s,'BaudRate',115200);")
        PrintLine(1, "s.InputBufferSize = 15000;")
        PrintLine(1, "fopen(s);")
        PrintLine(1, "fwrite(s,char_str);")
        PrintLine(1, "")
        PrintLine(1, "count = 0;")
        PrintLine(1, "while 1")
        PrintLine(1, "    inchar = fread(s,1);")
        PrintLine(1, "    if inchar == 42")
        PrintLine(1, "        inchar = fread(s,1);")
        PrintLine(1, "        inchar = fread(s,1);")
        PrintLine(1, "        if inchar == 51")
        PrintLine(1, "            out3 = fread(s,varsize,'float32');")
        PrintLine(1, "            break;")
        PrintLine(1, "        end")
        PrintLine(1, "    end")
        PrintLine(1, "    count = count + 1;")
        PrintLine(1, "    if count > 100")
        PrintLine(1, "        break;")
        PrintLine(1, "    end")
        PrintLine(1, "end")
        PrintLine(1, "")
        PrintLine(1, "")
        PrintLine(1, "fclose(s)")
        PrintLine(1, "delete(s)")
        PrintLine(1, "clear s")
        PrintLine(1, "")

        FileClose(1)


        FileOpen(1, Matlab_funcGE420_serialwrite_fileFullPath, OpenMode.Output)

        PrintLine(1, "function GE420_serialwrite(name,floatval,comport)")
        PrintLine(1, "%GE420_SERIALWRITE")
        PrintLine(1, "%   GE420_serialwrite(NAME,FLOATVAL,COMPORT) will modify a variable on the DSP ")
        PrintLine(1, "%   where NAME is the name of the variable on the DSP, and FLOATVAL is the ")
        PrintLine(1, "%   value you want to change that variable to.")
        PrintLine(1, "%   comport is a string with the COM port connected to the ""USB Serial Port"".")
        PrintLine(1, "%	It is usually the largest number of COM port in your system.  If you do not")
        PrintLine(1, "%	know your comport, run the command ""list_serailports"" to see all the")
        PrintLine(1, "%	available comports.")
        PrintLine(1, "%")
        PrintLine(1, "%	For example, to change the float variable ""myfloat"" on the DSP to a")
        PrintLine(1, "%	value to 5.5 you would type:")
        PrintLine(1, "%")
        PrintLine(1, "%		GE420_serialwrite('myfloat',5.5,'COM12');")
        PrintLine(1, "%")
        PrintLine(1, "")
        PrintLine(1, "")
        PrintLine(1, "s = instrfind;")
        PrintLine(1, "if length(s) > 0")
        PrintLine(1, "    fclose(s);")
        PrintLine(1, "end")
        PrintLine(1, "clear s;")
        PrintLine(1, "")
        PrintLine(1, "filename = dir('../" & ProjectName & "Project/debug/*.map');")
        PrintLine(1, "")
        PrintLine(1, "map = parseMap(strcat('../" & ProjectName & "Project/debug/',filename.name))")
        PrintLine(1, "")
        PrintLine(1, "memloc = 0;")
        PrintLine(1, "arrsize = size(map);")
        PrintLine(1, "found = 1;")
        PrintLine(1, "")
        PrintLine(1, "for i=1:arrsize(1)")
        PrintLine(1, "    if strfind(char(map(i,1)),name)")
        PrintLine(1, "        memloc = char(map(i,2));")
        PrintLine(1, "        found = 0;")
        PrintLine(1, "    end")
        PrintLine(1, "end")
        PrintLine(1, "if (found == 1)")
        PrintLine(1, "    exception = MException('MATLAB:VarNotFound','Variable name not found.');")
        PrintLine(1, "    throw(exception);")
        PrintLine(1, "end")
        PrintLine(1, "")
        PrintLine(1, "if (testifcom(comport) == 0)")
        PrintLine(1, "    display('Choose from the following COM ports');")
        PrintLine(1, "    list_serialports()")
        PrintLine(1, "    exception = MException('MATLAB:ComportNotFound','COM Port not found.');")
        PrintLine(1, "    throw(exception);")
        PrintLine(1, "end")
        PrintLine(1, "")
        PrintLine(1, "hex_str = '2A0B33'; % header")
        PrintLine(1, "hex_str = strcat(hex_str,memloc);")
        PrintLine(1, "char_str = char(sscanf(hex_str,'%2X').');")
        PrintLine(1, "s = serial(comport);")
        PrintLine(1, "set(s,'BaudRate',115200);")
        PrintLine(1, "s.InputBufferSize = 5000;")
        PrintLine(1, "fopen(s);")
        PrintLine(1, "fwrite(s,char_str);")
        PrintLine(1, "fwrite(s,floatval,'float32');")
        PrintLine(1, "fclose(s)")
        PrintLine(1, "delete(s)")
        PrintLine(1, "clear s")

        FileClose(1)

        FileOpen(1, Matlab_funcGE420_serialwrite_address_fileFullPath, OpenMode.Output)

        PrintLine(1, "function GE420_serialwrite_address(address,floatval)")
        PrintLine(1, "%GE420_SERIALWRITE_ADDRESS")
        PrintLine(1, "%   GE420_serialwrite_address(ADDRESS,FLOATVAL) will modify a variable at ")
        PrintLine(1, "%   the memory location ADDRESS in decimal, not hex, on the DSP. FLOATVAL ")
        PrintLine(1, "%   is the value you want to change that variable to.")
        PrintLine(1, "%")
        PrintLine(1, "%	For example, to change the float variable at address ""0001f5b0"" on the ")
        PrintLine(1, "%   DSP to a value to 5.5 you would type:")
        PrintLine(1, "%")
        PrintLine(1, "%		GE420_serialwrite_address(128432,5.5);")
        PrintLine(1, "%")
        PrintLine(1, "")
        PrintLine(1, "")
        PrintLine(1, "s = instrfind;")
        PrintLine(1, "if length(s) > 0")
        PrintLine(1, "    fclose(s);")
        PrintLine(1, "end")
        PrintLine(1, "clear s;")
        PrintLine(1, "")
        PrintLine(1, "filename = dir('../" & ProjectName & "/debug/*.map');")
        PrintLine(1, "")
        PrintLine(1, "map = parseMap(strcat('../" & ProjectName & "/debug/',filename.name))")
        PrintLine(1, "")
        PrintLine(1, "memloc = dec2hex(address,8);")
        PrintLine(1, "")
        PrintLine(1, "hex_str = '2A0B33'; % header")
        PrintLine(1, "hex_str = strcat(hex_str,memloc);")
        PrintLine(1, "char_str = char(sscanf(hex_str,'%2X').');")
        PrintLine(1, "s = serial('COM1');")
        PrintLine(1, "set(s,'BaudRate',115200);")
        PrintLine(1, "s.InputBufferSize = 5000;")
        PrintLine(1, "fopen(s);")
        PrintLine(1, "fwrite(s,char_str);")
        PrintLine(1, "fwrite(s,floatval,'float32');")
        PrintLine(1, "fclose(s)")
        PrintLine(1, "delete(s)")
        PrintLine(1, "clear s")
        PrintLine(1, "")
        PrintLine(1, "")

        FileClose(1)


        FileOpen(1, Matlab_funcGE420_serialwrite_echo_fileFullPath, OpenMode.Output)

        PrintLine(1, "function [echo] = GE420_serialwrite_echo(name,floatval)")
        PrintLine(1, "%GE420_SERIALWRITE_ECHO")
        PrintLine(1, "%   GE420_serialwrite_echo(NAME,FLOATVAL) will modify a variable on the DSP")
        PrintLine(1, "%   where NAME is the name of the variable on the DSP, and FLOATVAL is the ")
        PrintLine(1, "%   value you want to change that variable to.  Additionally, the value of ")
        PrintLine(1, "%   the variable on the DSP will be returned to verify the write was ")
        PrintLine(1, "%   successful.")
        PrintLine(1, "%")
        PrintLine(1, "%	For example, to change the float variable ""myfloat"" on the DSP to a")
        PrintLine(1, "%	value to 5.5 and store the echoed value to the Matlab single variable")
        PrintLine(1, "%	""myecho"" you would type:")
        PrintLine(1, "%")
        PrintLine(1, "%		myecho = GE420_serialwrite_echo('myfloat',5.5);")
        PrintLine(1, "%")
        PrintLine(1, "")
        PrintLine(1, "s = instrfind;")
        PrintLine(1, "if length(s) > 0")
        PrintLine(1, "    fclose(s);")
        PrintLine(1, "end")
        PrintLine(1, "clear s;")
        PrintLine(1, "")
        PrintLine(1, "filename = dir('../" & ProjectName & "/debug/*.map');")
        PrintLine(1, "")
        PrintLine(1, "map = parseMap(strcat('../" & ProjectName & "/debug/',filename.name))")
        PrintLine(1, "")
        PrintLine(1, "memloc = 0;")
        PrintLine(1, "arrsize = size(map);")
        PrintLine(1, "found = 1;")
        PrintLine(1, "")
        PrintLine(1, "for i=1:arrsize(1)")
        PrintLine(1, "    if strfind(char(map(i,1)),name)")
        PrintLine(1, "        memloc = char(map(i,2));")
        PrintLine(1, "        found = 0;")
        PrintLine(1, "    end")
        PrintLine(1, "end")
        PrintLine(1, "if (found == 1)")
        PrintLine(1, "    exception = MException('MATLAB:VarNotFound','Variable name not found.');")
        PrintLine(1, "    throw(exception);")
        PrintLine(1, "end")
        PrintLine(1, "")
        PrintLine(1, "hex_str = '2A0B33'; % header")
        PrintLine(1, "hex_str = strcat(hex_str,memloc);")
        PrintLine(1, "char_str = char(sscanf(hex_str,'%2X').');")
        PrintLine(1, "s = serial('COM1');")
        PrintLine(1, "set(s,'BaudRate',115200);")
        PrintLine(1, "s.InputBufferSize = 5000;")
        PrintLine(1, "fopen(s);")
        PrintLine(1, "fwrite(s,char_str);")
        PrintLine(1, "fwrite(s,floatval,'float32');")
        PrintLine(1, "fclose(s)")
        PrintLine(1, "delete(s)")
        PrintLine(1, "clear s")
        PrintLine(1, "echo = GE420_serialread(name,1);")

        FileClose(1)


        FileOpen(1, Matlab_funcGE420_serialwrite_echo_address_fileFullPath, OpenMode.Output)

        PrintLine(1, "function [echo] = GE420_serialwrite_echo_address(address,floatval)")
        PrintLine(1, "%GE420_SERIALWRITE_ECHO_ADDRESS")
        PrintLine(1, "%   GE420_serialwrite_echo(ADDRESS,FLOATVAL) will modify a variable on the ")
        PrintLine(1, "%   DSP at the memory location ADDRESS.  FLOATVAL is the value you want to ")
        PrintLine(1, "%   change that variable to.  Additionally, the value of the variable")
        PrintLine(1, "%	on the DSP will be returned to verify the write was successful.")
        PrintLine(1, "%")
        PrintLine(1, "%	For example, to change the float variable at the memory location ")
        PrintLine(1, "%   ""0001f5b0"" on the DSP to a	value to 5.5 and store the echoed value to ")
        PrintLine(1, "%   the Matlab single variable ""myecho"" you would type:")
        PrintLine(1, "%")
        PrintLine(1, "%		myecho = GE420_serialwrite_echo_address(128432,5.5);")
        PrintLine(1, "%")
        PrintLine(1, "")
        PrintLine(1, "s = instrfind;")
        PrintLine(1, "if length(s) > 0")
        PrintLine(1, "    fclose(s);")
        PrintLine(1, "end")
        PrintLine(1, "clear s;")
        PrintLine(1, "")
        PrintLine(1, "filename = dir('../" & ProjectName & "Project/debug/*.map');")
        PrintLine(1, "")
        PrintLine(1, "map = parseMap(strcat('../" & ProjectName & "Project/debug/',filename.name));")
        PrintLine(1, "")
        PrintLine(1, "memloc = dec2hex(address,8);")
        PrintLine(1, "")
        PrintLine(1, "hex_str = '2A0B33'; % header")
        PrintLine(1, "hex_str = strcat(hex_str,memloc);")
        PrintLine(1, "char_str = char(sscanf(hex_str,'%2X').');")
        PrintLine(1, "s = serial('COM1');")
        PrintLine(1, "set(s,'BaudRate',115200);")
        PrintLine(1, "s.InputBufferSize = 5000;")
        PrintLine(1, "fopen(s);")
        PrintLine(1, "fwrite(s,char_str);")
        PrintLine(1, "fwrite(s,floatval,'float32');")
        PrintLine(1, "fclose(s)")
        PrintLine(1, "delete(s)")
        PrintLine(1, "clear s")
        PrintLine(1, "echo = GE420_serialread_address(address,1);")

        FileClose(1)

        FileOpen(1, Matlab_funcGE420_serial_ListVars_fileFullPath, OpenMode.Output)

        PrintLine(1, "function GE420_serial_ListVars()")
        PrintLine(1, "%GE420_serial_ListVars")
        PrintLine(1, "%   GE420_serial_ListVars() simple lists the possible variables Matlab has")
        PrintLine(1, "%	access to inside your DSP application.  Helpful in finding the name of")
        PrintLine(1, "%	the variable you would like to write to or read from.")
        PrintLine(1, "%")
        PrintLine(1, "%		GE420_serial_ListVars();")
        PrintLine(1, "%")
        PrintLine(1, "%")
        PrintLine(1, "")
        PrintLine(1, "s = instrfind;")
        PrintLine(1, "if length(s) > 0")
        PrintLine(1, "    fclose(s);")
        PrintLine(1, "end")
        PrintLine(1, "clear s;")
        PrintLine(1, "")
        PrintLine(1, "filename = dir('../" & ProjectName & "Project/debug/*.map');")
        PrintLine(1, "")
        PrintLine(1, "map = parseMap(strcat('../" & ProjectName & "Project/debug/',filename.name))")
        PrintLine(1, "")
        PrintLine(1, "memloc = 0;")
        PrintLine(1, "arrsize = size(map);")
        PrintLine(1, "found = 1;")

        FileClose(1)

        FileOpen(1, Project_copybat_fileFullPath, OpenMode.Output)

        PrintLine(1, "copy " & ProjectDirectory & "..\GE420_F28377S_ProjectCreator\main.c " & ProjectDirectory)
        PrintLine(1, "move " & ProjectDirectory & "main.c " & ProjectDirectory & "user_" & ProjectName & ".c")
        PrintLine(1, "copy " & ProjectDirectory & "..\GE420_F28377S_ProjectCreator\sysbios.cfg " & ProjectDirectory & ProjectName & ".cfg")
        PrintLine(1, "copy " & ProjectDirectory & "..\GE420_F28377S_ProjectCreator\f28377sHeaders\*.* " & Project_f28377sHeadersDir)
        PrintLine(1, "copy " & ProjectDirectory & "..\GE420_F28377S_ProjectCreator\f28377sSrc\*.* " & Project_f28377sSrcDir)
        PrintLine(1, "copy " & ProjectDirectory & "..\GE420_F28377S_ProjectCreator\project\targetConfigs\*.* " & ProjectSub_targetConfigs)
        PrintLine(1, "copy " & ProjectDirectory & "..\GE420_F28377S_ProjectCreator\project\.settings\*.* " & ProjectSub_settings_Dir)
        PrintLine(1, "copy " & ProjectDirectory & "..\GE420_F28377S_ProjectCreator\v140\F2837xS_common\cmd\*.* " & Project_DSP28377_common_cmd_Dir)
        PrintLine(1, "copy " & ProjectDirectory & "..\GE420_F28377S_ProjectCreator\v140\F2837xS_common\include\*.* " & Project_DSP28377_common_include_Dir)
        PrintLine(1, "copy " & ProjectDirectory & "..\GE420_F28377S_ProjectCreator\v140\F2837xS_common\source\*.* " & Project_DSP28377_common_source_Dir)
        PrintLine(1, "copy " & ProjectDirectory & "..\GE420_F28377S_ProjectCreator\v140\F2837xS_headers\cmd\*.* " & Project_DSP28377_headers_cmd_Dir)
        PrintLine(1, "copy " & ProjectDirectory & "..\GE420_F28377S_ProjectCreator\v140\F2837xS_headers\include\*.* " & Project_DSP28377_headers_include_Dir)
        PrintLine(1, "copy " & ProjectDirectory & "..\GE420_F28377S_ProjectCreator\v140\F2837xS_headers\source\*.* " & Project_DSP28377_headers_source_Dir)
        PrintLine(1, "copy " & ProjectDirectory & "..\GE420_F28377S_ProjectCreator\matlab\*.* " & Project_matlab_Dir)
        PrintLine(1, Drive)
        PrintLine(1, "cd """ & ProjectDirectory & """")
        PrintLine(1, "pause")
        PrintLine(1, "del """ & Project_copybat_fileFullPath & """")

        FileClose(1)


        Shell(Project_copybat_fileFullPath, 1)


        Me.Close()

NoWrite:

    End Sub
End Class


